baseURL = "https://blog.qsliu.dev/"
theme = "hugo-coder"
title = "qsliu"

googleAnalytics = "G-RF6KM3Z05E"

[params]
author = "qsliu"
description = "qsliu's blog"
keywords = "blog,developer"
info = ["Developer", "Open Source Enthusiast", "Software Engineering Student"]
avatarurl = "https://avatars.githubusercontent.com/qsliu2017"

since = "2022"
dateFormat = "2006-01-02"

colorScheme = "auto"

[taxonomies]
category = "categories"
series = "series"
tag = "tags"
author = "authors"

[[params.social]]
name = "Github"
icon = "fa fa-github fa-2x"
weight = 1
url = "https://github.com/qsliu2017"

[[params.social]]
name = "Mail"
icon = "fa fa-envelope fa-2x"
weight = 2
url = "mailto:hi@qsliu.dev"

[[menu.main]]
name = "Post"
weight = 1
url = "posts/"

[[menu.main]]
name = "Link"
weight = 100
url = "links/"

[markup.goldmark.renderer]
# for directly use <iframe>
unsafe = true
