#!/bin/bash

if [ $# -ne 2 ]; then
  echo "Usage: $0 <page> <filename>"
  exit 1
fi

filename=$(date +%Y-%m-%d)-$(echo $2 | tr '[:upper:]' '[:lower:]' | tr ' ' '-' | tr '_' '-').md
note_dir=$(dirname $0)/../src/content/notes

if [ -e $note_dir/$filename ]; then
  echo "Note $filename already exists"
  exit 1
fi

mkdir -p $note_dir
cat > $note_dir/$filename <<EOF
---
page: "$1"
date: $(date +%Y-%m-%d)
---
EOF
